
import { GoogleGenAI, Modality } from "@google/genai";

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Analyzes an image to detect if a clear human face is present.
 * @param base64Image The base64 encoded image string (without data URL prefix).
 * @param mimeType The MIME type of the image.
 * @returns A promise that resolves to true if a face is detected, false otherwise.
 */
export const analyzeImageForFace = async (base64Image: string, mimeType: string): Promise<boolean> => {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: base64Image,
                            mimeType: mimeType,
                        },
                    },
                    {
                        text: "Does this image contain a clear, forward-facing human face suitable for a portrait? Answer with only 'YES' or 'NO'.",
                    },
                ],
            },
        });
        
        const text = response.text.trim().toUpperCase();
        return text.includes('YES');
    } catch (error) {
        console.error("Error analyzing image for face:", error);
        return false;
    }
};

/**
 * Generates a new image by placing the person from the source image into a new scene described by the prompt.
 * @param base64Image The base64 encoded image string of the source portrait.
 * @param mimeType The MIME type of the source image.
 * @param prompt The text prompt describing the target historical scene.
 * @returns A promise that resolves to the base64 encoded string of the generated image.
 */
export const generateHistoricalImage = async (base64Image: string, mimeType: string, prompt: string): Promise<string> => {
    const fullPrompt = `Take the person from the provided image and place them into the following scene: "${prompt}". Maintain their facial features and likeness. The final image should be a cohesive and realistic-looking composition.`;
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: base64Image,
                        mimeType: mimeType,
                    },
                },
                {
                    text: fullPrompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    const firstPart = response.candidates?.[0]?.content?.parts[0];
    if (firstPart && 'inlineData' in firstPart && firstPart.inlineData) {
        return firstPart.inlineData.data;
    }

    throw new Error('No image was generated by the API.');
};
